name: sami-plus

networks:
  proxy:
    external: true

services:
  sami-plus:
    restart: always
    container_name: sami-plus
    image: ${IMAGE}
    environment:
      - PUBLIC_DOMAIN
      - PORT
    ports: 
      - ${PORT}:${PORT}
    networks:
      proxy:
        aliases:
          - sami_plus
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sami-plus.loadbalancer.server.port=${PORT}"
      
      # Router primary domain sami.plus
      - "traefik.http.routers.sami-plus.rule=Host(`sami.plus`)"
      - "traefik.http.routers.sami-plus.tls.certresolver=le"
      - "traefik.http.routers.sami-plus.service=sami-plus"
      

      # Router secondary domain сами.рус
      - "traefik.http.routers.sami-rus.rule=Host(`xn--80aqls.xn--p1acf`)"
      - "traefik.http.routers.sami-rus.tls.certresolver=le"
      - "traefik.http.routers.sami-rus.service=sami-plus"

      # points.sami.plus redirect
      - "traefik.http.routers.points-sami-plus.rule=Host(`points.sami.plus`)"
      - "traefik.http.routers.points-sami-plus.tls.certresolver=le"
      - "traefik.http.routers.points-sami-plus.service=sami-plus"

      - "traefik.http.middlewares.points-redirect.redirectregex.regex=^https://points\\.sami\\.plus/(.*)"
      - "traefik.http.middlewares.points-redirect.redirectregex.replacement=https://share.sami.plus/point/$${1}"
      - "traefik.http.routers.points-sami-plus.middlewares=points-redirect"

      # share.sami.plus redirect
      - "traefik.http.routers.share-sami-plus.rule=Host(`share.sami.plus`)"
      - "traefik.http.routers.share-sami-plus.tls.certresolver=le"
      - "traefik.http.routers.share-sami-plus.service=sami-plus"

      - "traefik.http.middlewares.share-redirect.redirectregex.regex=^https://share\\.sami\\.plus/point/(.*)"
      - "traefik.http.middlewares.share-redirect.redirectregex.replacement=https://sami.plus/share/point/$${1}"

      - "traefik.http.routers.share-sami-plus.middlewares=share-redirect"

      # share-app.sami.plus redirect
      - "traefik.http.routers.share-app-sami-plus.rule=Host(`share-app.sami.plus`)"
      - "traefik.http.routers.share-app-sami-plus.tls.certresolver=le"
      - "traefik.http.routers.share-app-sami-plus.service=sami-plus"

      - "traefik.http.middlewares.share-app-redirect.redirectregex.regex=^https://share-app\\.sami\\.plus/(.*)"
      - "traefik.http.middlewares.share-app-redirect.redirectregex.replacement=${PUBLIC_DOMAIN}?referal=$${1}"

      - "traefik.http.routers.share-app-sami-plus.middlewares=share-app-redirect"

     
