name: Deploy to Yandex.Cloud

on:
  push:
    branches: ["main"]

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  IMAGE: ${{ vars.IMAGE }}
  PORT: ${{ vars.PORT }}
  PUBLIC_DOMAIN: ${{ vars.PUBLIC_DOMAIN }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: yandex-cloud

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker registry
        run: echo "${{ secrets.SA_KEY_BASE64 }}" | base64 -d | docker login --username json_key --password-stdin cr.yandex;

      - name: Build Docker image
        run: make image

      - name: Push Docker image
        run: make push

      - name: Setup SSH
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - >/dev/null
          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh
          # Add the remote server's SSH key to known_hosts
          ssh-keyscan -H sami.plus >> ~/.ssh/known_hosts

      - name: Deploy to Yandex.Cloud
        run: make deploy
